site_name: Gocanopen
repo_url: https://github.com/samsamfire/gocanopen
site_url: https://samsamfire.github.io/gocanopen
nav:
  - Getting started: index.md
  - CAN driver: can.md
  - Network : network.md
  - Nodes :
    - Local Node: local-node.md
    - Remote Node: remote-node.md
  - Object Dictionary : od.md
  - Configurator : configurator.md
  - SDO : sdo.md

theme:
  name: material
  icon : 
    logo: material/file-document
    favicon: material/file-document
  palette:
    primary: "light green"
    accent: "orange"

  features:
    - content.code.copy
    - navigation.instant
    - -navigation.instant.progress

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences