name: Run Tests with virtual can interface using docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: samsamfire/vcan-container:latest
      options: --user 1001

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: |
          /app/virtualcan --port 18888 &
          go test -v ./...
