# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install can-utils
      run: sudo apt-get install -y can-utils

    - name: Set up virtual CAN interface
      run: |
        # Load the can and vcan kernel modules
        sudo modprobe can
        sudo modprobe vcan

        # Create a virtual CAN interface (vcan0)
        sudo ip link add dev vcan0 type vcan
        sudo ip link set up vcan0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
